6pm 4 new database table
ucsb-cs156-w21/proj-mapache-search pull request #161
Opened 2021-03-03 04:08 UTC by jc9907

2021-03-03 06:06 UTC, pconrad requested changes
I have a couple of suggestions.   These will make the code a lot easier to maintain down the road.

2021-03-03 06:06 UTC, pconrad commented on src/test/java/edu/ucsb/mapache/entities/SearchTests.java
> +}
Once you add the .equals, .toString, and .hashCode, you can consult this file for a good example of how to test a class like this one:

https://github.com/ucsb-cs156-w21/proj-ucsb-cs-las/blob/main/src/test/java/edu/ucsb/ucsbcslas/entities/TutorAssignmentTests.java

Note that you can test all of the getters and setters with one line of code:

```
@Test
  public void testGettersAndSetters() throws Exception {
    // See: https://github.com/codebox/javabean-tester
    JavaBeanTester.test(TutorAssignment.class);
  }
```

2021-03-03 06:07 UTC, pconrad requested changes

2021-03-03 06:07 UTC, pconrad commented on src/main/java/edu/ucsb/mapache/entities/Search.java
> +      this.count = count
```
 Error:  /home/runner/work/proj-mapache-search/proj-mapache-search/src/main/java/edu/ucsb/mapache/entities/Search.java:[26,25] ';' expected`
```

Need to fix this syntax error.

2021-03-05 03:11 UTC, chengyanwu approved these changes
LGTM

2021-03-05 03:39 UTC, jayleenli commented
Approving although not my group. Jiachen went to my office hours and also discussed the codecov issues after lecture on Thursday with me, we finally got it working after office hours. They have also been blocked on this issue for a couple days and other team members cannot make progress unless this one is complete

2021-03-05 03:39 UTC, jayleenli approved these changes

2021-03-05 03:41 UTC, merged