kw - fixed a bug where footer blocks the last list elements in a few pages
ucsb-cs156-w21/proj-mapache-search pull request #182
Opened 2021-03-05 06:09 UTC by kweng149

The footer blocks the last list elements in long scrollable pages such as list channels and the search page. This issue should fix that bug.

2021-03-05 08:29 UTC, vivianross06 approved these changes
LGTM

2021-03-05 19:59 UTC, jayleenli requested changes
There shouldn't be any changes to package-lock in this pull request? Can you go back and commit only the App.css file

2021-03-06 02:45 UTC, vivianross06 submitted a review, later dismissed
LGTM

2021-03-06 21:12 UTC, jayleenli submitted a review, later dismissed

2021-03-06 21:17 UTC, merged