6pm 2 fixed navbar
ucsb-cs156-w21/proj-mapache-search pull request #186
Opened 2021-03-05 20:44 UTC by kweng149

Fixed the navbar to the top of the page so that it can always be accessed no matter where the user is on the page. For example, when scrolling through a very long page, the user can immediately navigate to other parts of the app without scrolling all the way back up.

2021-03-05 20:52 UTC, vivianross06 submitted a review, later dismissed
LGTM

2021-03-06 00:24 UTC, jayleenli requested changes
Same issue with package-lock, I made a comment here of how you can fix

https://github.com/ucsb-cs156-w21/proj-mapache-search/pull/169#issuecomment-791808590

2021-03-06 02:46 UTC, vivianross06 approved these changes
LGTM

2021-03-06 21:27 UTC, jayleenli approved these changes

2021-03-06 21:28 UTC, merged