6pm 2 list view
ucsb-cs156-w21/proj-mapache-search pull request #199
Opened 2021-03-08 19:44 UTC by vivianross06

Make messages list view render without breaking
Removed complete dependency on SlackUsers API so that user names can be displayed
Made links within messages clickable

2021-03-08 21:05 UTC, kweng149 submitted a review, later dismissed
LGTM

2021-03-09 00:22 UTC, jayleenli requested changes
Because of Bethany's change in #177 , there are a lot of merge conflicts I think you two may have overlapping code, please resolve the conflicts. However your group is totally good with points so you definitely don't have to complete this PR, but if you still want to get this PR merged those are the changes needed

2021-03-09 01:37 UTC, kweng149 approved these changes
LGTM

2021-03-10 01:36 UTC, jayleenli approved these changes

2021-03-10 01:37 UTC, merged