Allows footer links to take you to a new tab
ucsb-cs156-w21/proj-mapache-search pull request #206
Opened 2021-03-10 09:18 UTC by gargadarsh

Allows footer links to open a new tab.

2021-03-10 10:11 UTC, avatarmiko commented
![image](https://user-images.githubusercontent.com/35274879/110612779-601a6080-8145-11eb-8c38-5ccfc0bdc68f.png)
![image](https://user-images.githubusercontent.com/35274879/110612913-804a1f80-8145-11eb-9032-be98d73ba106.png)
more ESLint vars to delete/use trivially, and a test needed for openInNewTab function in AppFooter.js

2021-03-11 00:30 UTC, jayleenli requested changes
Made comments about the code

Other comments not directly tied to the code:
Also make sure to get a team review again
Please update the PR description with the changes you made
Also please link the issue that this is solving to this PR

2021-03-11 00:30 UTC, jayleenli commented on javascript/src/main/components/Channels/ChannelLinksTable.js
> +// import React from "react";
This file looks like it is from another feature. Take this file out from your branch

2021-03-11 00:30 UTC, jayleenli commented on javascript/src/main/pages/Channels/ChannelPageScrollable.js
> +            {/* <ChannelLinksTable data={links} messages={messages} /> */}
Same response to everything said above. Please uncommit this file since it is not related to the feature you are implementing.

2021-03-11 00:30 UTC, jayleenli commented on javascript/src/stories/components/SearchedTermsTable/SearchedTermsTable.stories.js
> +import React from "react";
This entire file does not look related to the feature you are trying to implement, which I'm guessing is this one: https://github.com/ucsb-cs156-w21/proj-mapache-search/issues/203, Again, same comment

2021-03-11 22:40 UTC, closed without merging