7pm d custom api
ucsb-cs156-w21/proj-mapache-search pull request #81
Opened 2020-12-10 07:57 UTC by soohyunchoi

- Added frontend for custom api input fields and user information
- Added tests for frontend rendering
- This pull request **partially** resolves #37 
![Screen Shot 2020-12-09 at 11 56 54 PM](https://user-images.githubusercontent.com/24615656/101737804-384e2a80-3a7a-11eb-84e6-99f672011609.png)

2020-12-10 08:06 UTC, andrewhlu requested changes
Looks like you tried to merge / rebase but you didn't resolve all the merge conflicts and instead committed them. Please resolve this and re-request the staff for a review. Please also ensure that your tests pass.

2020-12-10 08:06 UTC, andrewhlu commented on src/main/java/edu/ucsb/mapache/controllers/RoleController.java
> +>>>>>>> 6dca1329b74d108ad745acb32b232132ce3bb751
Diff markers present here

2020-12-10 08:06 UTC, andrewhlu commented on src/main/java/edu/ucsb/mapache/entities/AppUser.java
> +>>>>>>> 6dca1329b74d108ad745acb32b232132ce3bb751
Diff markers present here

2020-12-10 08:06 UTC, andrewhlu commented on src/main/java/edu/ucsb/mapache/entities/AppUser.java
> +>>>>>>> 6dca1329b74d108ad745acb32b232132ce3bb751
Diff markers present here.

2020-12-10 08:16 UTC, soohyunchoi commented
> Looks like you tried to merge / rebase but you didn't resolve all the merge conflicts and instead committed them. Please resolve this and re-request the staff for a review. Please also ensure that your tests pass.

Sorry about that. All frontend tests are passing with 100% code coverage. I can't test the backend but it should be working with all tests passing after I take out these diff markers.

2020-12-10 08:35 UTC, andrewhlu commented
Thanks for fixing the merge conflict. As you mentioned, it looks like your test coverage isn't at 100% - could you fix this and then re-request the staff again?

2021-02-24 04:16 UTC, pconrad commented
Rolled over to issue #135 in W21

2021-02-24 04:16 UTC, closed without merging